/**
 * DRAFT — NOT LEGAL ADVICE.
 * Have counsel review before publishing. See src/marketing/config.ts.
 */
import { PageShell, Prose } from '../components/PageShell'
import { useSeo } from '../hooks/useSeo'
import { SITE, routes } from '../config'

export function MarketingDisclaimer() {
  useSeo({
    title: 'Disclaimer',
    description: `Important limitations on ${SITE.name} data accuracy, AI-generated output, third-party metrics and SEO outcomes.`,
    path: routes.disclaimer,
  })

  return (
    <PageShell
      label="Legal"
      title="Disclaimer"
      intro={`Last updated ${SITE.legalUpdated}. What ${SITE.name} can and cannot tell you, and what you should not rely on it for.`}
    >
      <Prose>
        <h2>No guarantee of ranking or traffic</h2>
        <p>
          Search engines rank pages using systems that are proprietary, change frequently and are
          outside anyone's control. Nothing in this platform — including audits, blueprints,
          roadmaps and AI recommendations — is a promise that your rankings, traffic, impressions or
          revenue will improve. Any figures shown as projections are illustrative models, not
          forecasts you should budget against.
        </p>

        <h2>Third-party data is an estimate</h2>
        <p>
          Search volume, keyword difficulty, cost-per-click, domain metrics, traffic estimates and
          backlink counts are supplied by third-party providers such as DataForSEO, Serper and
          similar services. These are modelled estimates, not measurements. They differ between
          providers, change without notice, and may be inaccurate or incomplete. We do not verify,
          endorse or take responsibility for the accuracy of data returned by providers you connect.
        </p>
        <p>
          Data sourced directly from Google Search Console and Google Analytics reflects what Google
          reports to you, subject to Google's own sampling, filtering and thresholds.
        </p>

        <h2>AI-generated output</h2>
        <p>
          Articles, meta descriptions, FAQs, briefs, critiques and strategic recommendations produced
          by the AI features are generated by large language models. They can be inaccurate,
          outdated, biased or entirely fabricated, including invented statistics and citations. Every
          output must be reviewed and fact-checked by a person before you publish it or act on it.
          You remain the author and publisher of anything you release.
        </p>

        <h2>Strategy modes</h2>
        <p>
          The platform offers strategy modes that produce progressively more aggressive
          recommendations. Tactics that conflict with search engine guidelines carry a genuine risk
          of ranking loss, manual action or de-indexing. These modes exist to describe the landscape,
          not to endorse it. You alone are responsible for deciding what to implement, and for the
          consequences on any site you apply it to.
        </p>

        <h2>Not professional advice</h2>
        <p>
          Content in this platform is provided for general informational purposes. It is not legal,
          financial, accounting, medical or other professional advice. If your sector is regulated —
          finance, health, law and similar — have qualified professionals review material before you
          publish it.
        </p>

        <h2>Your infrastructure</h2>
        <p>
          You supply the database and the provider accounts this platform runs against. We are not
          responsible for their availability, performance, retention, backups, security or billing.
          Keep your own backups.
        </p>

        <h2>External links and trademarks</h2>
        <p>
          Product names referenced in this platform or on this website — including other SEO tools —
          are the trademarks of their respective owners and are used for identification and
          comparison only. Their mention does not imply affiliation with or endorsement by them. Any
          pricing quoted for third-party products is indicative, may be out of date, and should be
          verified with that vendor.
        </p>

        <h2>Questions</h2>
        <p>
          Contact <a href={`mailto:${SITE.contact.general}`}>{SITE.contact.general}</a>, or read our{' '}
          <a href={routes.terms}>terms of service</a> and{' '}
          <a href={routes.privacy}>privacy policy</a>.
        </p>
      </Prose>
    </PageShell>
  )
}
