import { toPng } from 'html-to-image'
import { jsPDF } from 'jspdf'

const BRAND_COLOR = [0, 212, 255]  as const
const DARK_BG     = [10, 15, 30]   as const
const HEADER_H    = 20             // mm
const FOOTER_H    = 10             // mm
const MARGIN      = 10             // mm

function addHeader(pdf: jsPDF, title: string, page: number, total: number) {
  const w = pdf.internal.pageSize.getWidth()

  pdf.setFillColor(...DARK_BG)
  pdf.rect(0, 0, w, HEADER_H, 'F')

  pdf.setTextColor(...BRAND_COLOR)
  pdf.setFontSize(9)
  pdf.setFont('helvetica', 'bold')
  pdf.text('JARVIS', MARGIN, 13)

  pdf.setTextColor(180, 180, 200)
  pdf.setFontSize(8)
  pdf.setFont('helvetica', 'normal')
  pdf.text(title, MARGIN + 16, 13)

  const right = w - MARGIN
  pdf.text(
    new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }),
    right, 9, { align: 'right' }
  )
  pdf.text(`Page ${page} of ${total}`, right, 16, { align: 'right' })

  pdf.setDrawColor(...BRAND_COLOR)
  pdf.setLineWidth(0.3)
  pdf.line(0, HEADER_H, w, HEADER_H)
}

function addFooter(pdf: jsPDF) {
  const w = pdf.internal.pageSize.getWidth()
  const h = pdf.internal.pageSize.getHeight()
  pdf.setDrawColor(40, 50, 70)
  pdf.setLineWidth(0.2)
  pdf.line(MARGIN, h - FOOTER_H + 2, w - MARGIN, h - FOOTER_H + 2)
  pdf.setTextColor(80, 90, 110)
  pdf.setFontSize(7)
  pdf.text('Generated by Jarvis iGaming SEO Platform', MARGIN, h - 4)
  pdf.text('Confidential', w - MARGIN, h - 4, { align: 'right' })
}

export async function exportToPDF(elementId: string, sectionTitle: string): Promise<void> {
  const el = document.getElementById(elementId)
  if (!el) throw new Error('Section content element not found')

  // Temporarily expand element to full scroll height so everything is captured
  const originalHeight   = el.style.height
  const originalOverflow = el.style.overflow
  el.style.height   = `${el.scrollHeight}px`
  el.style.overflow = 'visible'

  let dataUrl: string
  try {
    // html-to-image uses the browser's native SVG renderer —
    // supports oklab/oklch (Tailwind v4), SVG charts, backdrop-blur, etc.
    dataUrl = await toPng(el, {
      pixelRatio:  2,
      width:       el.offsetWidth,
      height:      el.scrollHeight,
      skipFonts:   false,
      cacheBust:   true,
      style: {
        // Ensure no transform clips the capture
        transform:       'none',
        transformOrigin: 'top left',
      },
    })
  } finally {
    // Always restore original styles
    el.style.height   = originalHeight
    el.style.overflow = originalOverflow
  }

  // Build the PDF
  const pdf      = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const pageW    = pdf.internal.pageSize.getWidth()   // 210 mm
  const pageH    = pdf.internal.pageSize.getHeight()  // 297 mm
  const contentW = pageW - MARGIN * 2
  const contentH = pageH - HEADER_H - FOOTER_H - MARGIN * 2

  // Load the image to get its natural dimensions
  const img = await new Promise<HTMLImageElement>((resolve, reject) => {
    const i    = new Image()
    i.onload   = () => resolve(i)
    i.onerror  = reject
    i.src      = dataUrl
  })

  // Natural image dimensions in mm (image is 2× so divide by 2 for mm mapping)
  // img.width / 2 = logical px width; scale to fit contentW
  const scale       = contentW / (img.width / 2)
  const fullH_mm    = (img.height / 2) * scale
  const totalPages  = Math.max(1, Math.ceil(fullH_mm / contentH))

  // Create a temporary canvas to slice the image per page
  const srcCanvas    = document.createElement('canvas')
  srcCanvas.width    = img.width
  srcCanvas.height   = img.height
  srcCanvas.getContext('2d')!.drawImage(img, 0, 0)

  const slicePx = Math.round((contentH / scale) * 2) // canvas px per page slice

  for (let p = 0; p < totalPages; p++) {
    if (p > 0) pdf.addPage()

    addHeader(pdf, sectionTitle, p + 1, totalPages)
    addFooter(pdf)

    const srcY      = p * slicePx
    const srcH      = Math.min(slicePx, img.height - srcY)
    if (srcH <= 0) break

    const slice     = document.createElement('canvas')
    slice.width     = img.width
    slice.height    = srcH
    slice.getContext('2d')!.drawImage(srcCanvas, 0, srcY, img.width, srcH, 0, 0, img.width, srcH)

    const sliceH_mm = (srcH / 2) * scale

    pdf.addImage(slice.toDataURL('image/png', 1.0), 'PNG', MARGIN, HEADER_H + MARGIN, contentW, sliceH_mm)
  }

  const date     = new Date().toISOString().slice(0, 10)
  const filename = `jarvis-${sectionTitle.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${date}.pdf`
  pdf.save(filename)
}
