import { useState } from 'react'
import { Globe, Plus, Trash2, Copy, Check, AlertCircle, CheckCircle2, Download, History } from 'lucide-react'
import { Card, CardTitle } from '@/components/ui/Card'
import { Button } from '@/components/ui/Button'
import { HistoryPanel } from '@/components/ui/HistoryPanel'
import { useHistory } from '@/lib/history'
import { downloadCSV } from '@/lib/csv'
import { InfoTooltip } from '@/components/ui/InfoTooltip'
import { cn } from '@/lib/utils'

interface HreflangEntry { id: string; url: string; lang: string; region: string; isDefault: boolean }

interface HreflangRecord {
  id: string; savedAt: string; label: string; sublabel: string
  entries: HreflangEntry[]; html: string
}

const LANGUAGES = [
  { code: 'en', name: 'English' }, { code: 'de', name: 'German' },
  { code: 'fr', name: 'French'  }, { code: 'es', name: 'Spanish'},
  { code: 'it', name: 'Italian' }, { code: 'pt', name: 'Portuguese' },
  { code: 'nl', name: 'Dutch'   }, { code: 'fi', name: 'Finnish' },
  { code: 'sv', name: 'Swedish' }, { code: 'no', name: 'Norwegian' },
  { code: 'hi', name: 'Hindi'   }, { code: 'id', name: 'Indonesian' },
]

const REGIONS = [
  { code: 'GB', name: 'United Kingdom' }, { code: 'IE', name: 'Ireland' },
  { code: 'CA', name: 'Canada' },         { code: 'AU', name: 'Australia' },
  { code: 'NZ', name: 'New Zealand' },    { code: 'DE', name: 'Germany' },
  { code: 'AT', name: 'Austria' },        { code: 'CH', name: 'Switzerland' },
  { code: 'FI', name: 'Finland' },        { code: 'SE', name: 'Sweden' },
  { code: 'NO', name: 'Norway' },         { code: 'US', name: 'United States' },
  { code: 'IN', name: 'India' },          { code: 'ID', name: 'Indonesia' },
]

let nextId = 100

function hreflangCode(lang: string, region: string) {
  return region ? `${lang}-${region}` : lang
}

function generateHTML(entries: HreflangEntry[]): string {
  const lines: string[] = ['<!-- Hreflang tags generated by Caspira SearchOps -->']
  entries.forEach(e => {
    const code = hreflangCode(e.lang, e.region)
    lines.push(`<link rel="alternate" hreflang="${code}" href="${e.url}" />`)
  })
  const defaultEntry = entries.find(e => e.isDefault)
  if (defaultEntry) {
    lines.push(`<link rel="alternate" hreflang="x-default" href="${defaultEntry.url}" />`)
  }
  return lines.join('\n')
}

function validateEntries(entries: HreflangEntry[]): { type: 'error' | 'warning' | 'pass'; msg: string }[] {
  const issues: { type: 'error' | 'warning' | 'pass'; msg: string }[] = []
  const hasDefault = entries.some(e => e.isDefault)
  if (!hasDefault) issues.push({ type: 'error', msg: 'No x-default URL set — required for hreflang to work correctly' })
  else issues.push({ type: 'pass', msg: 'x-default URL is set' })

  const codes = entries.map(e => hreflangCode(e.lang, e.region))
  const dupes = codes.filter((c, i) => codes.indexOf(c) !== i)
  if (dupes.length) issues.push({ type: 'error', msg: `Duplicate hreflang code(s): ${[...new Set(dupes)].join(', ')}` })
  else issues.push({ type: 'pass', msg: 'No duplicate language codes' })

  entries.forEach(e => {
    if (!e.url.startsWith('https://') && !e.url.startsWith('http://')) {
      issues.push({ type: 'error', msg: `URL "${e.url}" must be absolute (include https://)` })
    }
  })

  if (entries.length >= 2) issues.push({ type: 'pass', msg: `${entries.length} hreflang entries defined` })
  if (entries.some(e => e.lang === 'en' && e.region === 'GB')) {
    issues.push({ type: 'pass', msg: 'en-GB (UK) entry present — important for UK SEO' })
  }

  const gbEntry = entries.find(e => e.lang === 'en' && e.region === 'GB')
  const ieEntry = entries.find(e => e.lang === 'en' && e.region === 'IE')
  if (gbEntry && !ieEntry) {
    issues.push({ type: 'warning', msg: 'You have en-GB but no en-IE — Ireland is worth targeting if you serve that market' })
  }
  return issues
}

export function HreflangBuilder() {
  const [entries,  setEntries]  = useState<HreflangEntry[]>([])
  const [newUrl,   setNewUrl]   = useState('')
  const [newLang,  setNewLang]  = useState('en')
  const [newRegion, setNewRegion] = useState('NZ')
  const [copied,   setCopied]   = useState(false)
  const [view,     setView]     = useState<'builder' | 'code'>('builder')
  const [tab,      setTab]      = useState<'tool' | 'history'>('tool')

  const { records, save, remove, clear } = useHistory<HreflangRecord>('jarvis_hreflang_history')

  function addEntry() {
    if (!newUrl.trim()) return
    const entry: HreflangEntry = {
      id: String(nextId++),
      url: newUrl.trim(),
      lang: newLang,
      region: newRegion,
      isDefault: false,
    }
    setEntries(prev => [...prev, entry])
    setNewUrl('')
  }

  function removeEntry(id: string) {
    setEntries(prev => prev.filter(e => e.id !== id))
  }

  function setDefault(id: string) {
    setEntries(prev => prev.map(e => ({ ...e, isDefault: e.id === id })))
  }

  const html   = generateHTML(entries)
  const issues = validateEntries(entries)
  const errors = issues.filter(i => i.type === 'error').length

  function handleCopy() {
    navigator.clipboard.writeText(html)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  function handleDownload() {
    const blob = new Blob([html], { type: 'text/plain' })
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement('a')
    a.href = url; a.download = 'hreflang-tags.html'; a.click()
    URL.revokeObjectURL(url)
  }

  function exportCSV() {
    downloadCSV(
      `hreflang-${new Date().toISOString().slice(0, 10)}.csv`,
      ['URL', 'Language', 'Region', 'Hreflang Code', 'Is Default'],
      entries.map(e => [e.url, e.lang, e.region, hreflangCode(e.lang, e.region), e.isDefault ? 'Yes' : 'No']),
    )
  }

  function saveSnapshot() {
    save({ id: crypto.randomUUID(), savedAt: new Date().toISOString(),
      label: entries.find(e => e.isDefault)?.url || `${entries.length} entries`,
      sublabel: `${entries.length} targets · ${new Set(entries.map(e => e.lang)).size} langs`,
      entries: [...entries], html })
  }

  return (
    <div className="space-y-5">
      <div className="flex gap-1 p-1 bg-surface border border-border rounded-lg w-fit">
        <button onClick={() => setTab('tool')} className={cn('px-3 py-1.5 rounded-lg text-[11px] font-semibold transition-all cursor-pointer', tab === 'tool' ? 'bg-accent text-black' : 'text-muted hover:text-tx')}>Hreflang Builder</button>
        <button onClick={() => setTab('history')} className={cn('flex items-center gap-1 px-3 py-1.5 rounded-lg text-[11px] font-semibold transition-all cursor-pointer', tab === 'history' ? 'bg-accent text-black' : 'text-muted hover:text-tx')}>
          <History size={11} /> History {records.length > 0 && `(${records.length})`}
        </button>
      </div>
      {tab === 'history' ? (
        <HistoryPanel
          records={records}
          onLoad={r => { setEntries(r.entries); setTab('tool') }}
          onDelete={remove}
          onClear={clear}
          onDownload={r => { const blob = new Blob([r.html], { type: 'text/plain' }); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = `hreflang-${r.savedAt.slice(0,10)}.html`; a.click() }}
          emptyText="No hreflang sets saved yet. Build and save your tags."
        />
      ) : (<>
      {/* Stats */}
      <div className="grid grid-cols-3 gap-4">
        {[
          { label: 'LANGUAGE TARGETS', val: entries.length,                         color: '#00d4ff', tip: 'Each hreflang entry tells Google which language/region version of a page to show to users in that locale.' },
          { label: 'ERRORS',           val: errors,                                 color: errors ? '#ef4444' : '#10b981', tip: 'Validation errors that will prevent hreflang from working correctly — e.g. missing x-default, duplicate codes, or relative URLs.' },
          { label: 'UNIQUE LANGS',     val: new Set(entries.map(e => e.lang)).size, color: '#7c3aed', tip: 'Number of distinct language codes across all entries. Each language can have multiple region variants (e.g. en-GB, en-IE, en-AU).' },
        ].map(s => (
          <Card key={s.label} className="text-center py-4">
            <div className="text-3xl font-display font-black mb-1" style={{ color: s.color }}>{s.val}</div>
            <div className="flex items-center justify-center gap-1 text-[10px] text-muted font-mono-jarvis tracking-widest">
              {s.label}
              <InfoTooltip text={s.tip} />
            </div>
          </Card>
        ))}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-5">
        {/* Builder */}
        <div className="lg:col-span-2 space-y-4">
          <Card>
            <CardTitle className="mb-3">Add Language Target</CardTitle>
            <div className="grid grid-cols-4 gap-2 mb-3">
              <div className="col-span-2">
                <div className="text-[10px] text-muted font-mono-jarvis tracking-widest mb-1">ABSOLUTE URL</div>
                <input value={newUrl} onChange={e => setNewUrl(e.target.value)}
                  onKeyDown={e => e.key === 'Enter' && addEntry()}
                  placeholder="https://yoursite.com/en-nz/page"
                  className="w-full bg-surface border border-border rounded-lg px-3 py-2 text-xs text-tx font-mono-jarvis outline-none focus:border-accent transition-colors" />
              </div>
              <div>
                <div className="flex items-center gap-1 text-[10px] text-muted font-mono-jarvis tracking-widest mb-1">
                  LANGUAGE
                  <InfoTooltip text="ISO 639-1 language code (e.g. 'en' for English, 'hi' for Hindi, 'id' for Indonesian). Combined with a region code to create locale-specific hreflang tags." />
                </div>
                <select value={newLang} onChange={e => setNewLang(e.target.value)}
                  className="w-full bg-surface border border-border rounded-lg px-2 py-2 text-xs text-tx outline-none focus:border-accent transition-colors">
                  {LANGUAGES.map(l => <option key={l.code} value={l.code}>{l.code} — {l.name}</option>)}
                </select>
              </div>
              <div>
                <div className="flex items-center gap-1 text-[10px] text-muted font-mono-jarvis tracking-widest mb-1">
                  REGION
                  <InfoTooltip text="ISO 3166-1 alpha-2 region code (e.g. 'GB', 'IN', 'ID'). Optional — omit for language-only targeting. Use with language to geo-target (e.g. en-IN for English speakers in India)." />
                </div>
                <select value={newRegion} onChange={e => setNewRegion(e.target.value)}
                  className="w-full bg-surface border border-border rounded-lg px-2 py-2 text-xs text-tx outline-none focus:border-accent transition-colors">
                  <option value="">No region</option>
                  {REGIONS.map(r => <option key={r.code} value={r.code}>{r.code} — {r.name}</option>)}
                </select>
              </div>
            </div>
            <Button variant="primary" onClick={addEntry} disabled={!newUrl.trim()}>
              <Plus size={13} /> Add Entry
            </Button>
          </Card>

          <Card>
            <div className="flex items-center justify-between mb-3">
              <CardTitle>Hreflang Entries</CardTitle>
              <div className="flex gap-1.5">
                {(['builder','code'] as const).map(v => (
                  <button key={v} onClick={() => setView(v)}
                    className={`text-[10px] px-2.5 py-1 rounded-lg font-mono-jarvis cursor-pointer transition-colors ${view === v ? 'bg-accent text-black' : 'text-muted hover:text-tx'}`}>
                    {v === 'builder' ? 'Table' : 'HTML Code'}
                  </button>
                ))}
              </div>
            </div>

            {view === 'builder' ? (
              <div className="space-y-2">
                {entries.map(entry => (
                  <div key={entry.id} className="flex items-center gap-3 p-3 bg-surface border border-border rounded-xl">
                    <Globe size={13} className="text-accent shrink-0" />
                    <div className="flex-1 min-w-0">
                      <div className="text-xs font-mono-jarvis text-tx truncate mb-0.5">{entry.url}</div>
                      <div className="text-[10px] text-accent font-mono-jarvis font-bold">
                        hreflang="{hreflangCode(entry.lang, entry.region)}"
                        {entry.isDefault && ' · x-default'}
                      </div>
                    </div>
                    <div className="flex items-center gap-1.5 shrink-0">
                      <InfoTooltip text="x-default is a special hreflang value that specifies the fallback page for users who don't match any other locale. Required for hreflang to work correctly — typically your main English or international page." side="left" />
                      <button onClick={() => setDefault(entry.id)}
                        className={`text-[10px] px-2 py-0.5 rounded-full border cursor-pointer transition-colors ${
                          entry.isDefault ? 'border-accent3 bg-accent3/10 text-accent3' : 'border-border text-muted hover:border-accent3'
                        }`}>
                        {entry.isDefault ? 'x-default' : 'set default'}
                      </button>
                      <button onClick={() => removeEntry(entry.id)} className="text-muted hover:text-danger transition-colors cursor-pointer">
                        <Trash2 size={13} />
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <div>
                <div className="flex gap-2 mb-3 flex-wrap">
                  <Button variant="ghost" className="text-[11px]" onClick={handleCopy}>
                    {copied ? <><Check size={11} /> Copied</> : <><Copy size={11} /> Copy</>}
                  </Button>
                  <Button variant="primary" className="text-[11px]" onClick={handleDownload}>
                    <Download size={11} /> Download HTML
                  </Button>
                  <Button variant="ghost" className="text-[11px]" onClick={exportCSV}>
                    <Download size={11} /> Export CSV
                  </Button>
                  <Button variant="ghost" className="text-[11px]" onClick={saveSnapshot} disabled={entries.length === 0}>
                    Save Snapshot
                  </Button>
                </div>
                <pre className="bg-code rounded-xl border border-border p-4 text-[10px] font-mono-jarvis text-accent3 overflow-x-auto whitespace-pre leading-relaxed">
                  {html}
                </pre>
              </div>
            )}
          </Card>
        </div>

        {/* Validation */}
        <Card>
          <CardTitle className="mb-3">Validation</CardTitle>
          <div className="space-y-2">
            {issues.map((issue, i) => (
              <div key={i} className="flex items-start gap-2 p-2.5 bg-surface border border-border rounded-lg">
                {issue.type === 'error'   && <AlertCircle  size={12} className="text-danger mt-0.5 shrink-0" />}
                {issue.type === 'warning' && <AlertCircle  size={12} className="text-accent4 mt-0.5 shrink-0" />}
                {issue.type === 'pass'    && <CheckCircle2 size={12} className="text-accent3 mt-0.5 shrink-0" />}
                <div className="text-[11px] leading-relaxed" style={{
                  color: issue.type === 'error' ? '#ef4444' : issue.type === 'warning' ? 'var(--color-accent4)' : 'var(--color-muted)',
                }}>
                  {issue.msg}
                </div>
              </div>
            ))}
          </div>

          {errors === 0 && (
            <div className="mt-4 p-3 bg-[#10b98110] border border-[#10b98130] rounded-lg text-xs text-muted">
              <span className="text-accent3 font-semibold">All checks passed.</span>
              {' '}Add these tags to the {'<head>'} of every page listed above.
            </div>
          )}

          <div className="mt-4">
            <div className="text-[10px] text-muted font-mono-jarvis tracking-widest mb-2">LANGUAGE MAP</div>
            <div className="flex flex-wrap gap-1.5">
              {entries.map(e => (
                <span key={e.id} className="text-[10px] px-2 py-0.5 rounded-full border border-border text-tx font-mono-jarvis">
                  {hreflangCode(e.lang, e.region)}
                  {e.isDefault && ' ★'}
                </span>
              ))}
            </div>
          </div>
        </Card>
      </div>
      </>)}
    </div>
  )
}
