import { useState } from 'react'
import { Shuffle, Plus, Trash2, AlertCircle, CheckCircle2, Copy, Check, ChevronRight, Download } from 'lucide-react'
import { Card, CardTitle } from '@/components/ui/Card'
import { Badge } from '@/components/ui/Badge'
import { Button } from '@/components/ui/Button'
import { cn } from '@/lib/utils'
import { downloadCSV } from '@/lib/csv'
import { InfoTooltip } from '@/components/ui/InfoTooltip'

type RedirectType = 301 | 302 | 307 | 410
interface Redirect { id: string; from: string; to: string; type: RedirectType; chain: boolean; chainDepth: number }

const TYPE_LABEL: Record<RedirectType, string> = { 301: 'Permanent', 302: 'Temporary', 307: 'Temp (Method)', 410: 'Gone' }
const TYPE_BADGE: Record<RedirectType, 'green' | 'amber' | 'purple' | 'red'> = { 301: 'green', 302: 'amber', 307: 'purple', 410: 'red' }

const DEFAULT_REDIRECTS: Redirect[] = [
  { id: '1', from: '/promo-2022',                  to: '/offers/current',           type: 301, chain: false, chainDepth: 1 },
  { id: '2', from: '/old-promo-page',              to: '/offers',                   type: 301, chain: false, chainDepth: 1 },
  { id: '3', from: '/best-products-2024',          to: '/best-products',            type: 301, chain: false, chainDepth: 1 },
  { id: '4', from: '/old-promo-page/landing',      to: '/offers/welcome',           type: 302, chain: false, chainDepth: 1 },
  { id: '5', from: '/product-landing-page',        to: '/products',                 type: 301, chain: true,  chainDepth: 2 },
  { id: '6', from: '/products',                    to: '/all-products',             type: 301, chain: false, chainDepth: 1 },
  { id: '7', from: '/regional-landing-page',       to: '/landing-page',             type: 301, chain: false, chainDepth: 1 },
  { id: '8', from: '/glossary-2023',               to: '',                          type: 410, chain: false, chainDepth: 1 },
]

type ViewMode = 'table' | 'htaccess' | 'nginx'

function detectChains(redirects: Redirect[]): Redirect[] {
  const fromSet = new Set(redirects.map(r => r.from))
  return redirects.map(r => ({
    ...r,
    chain: r.type !== 410 && fromSet.has(r.to),
  }))
}

function toHtaccess(domain: string, redirects: Redirect[]): string {
  const lines = [
    `# Redirect rules generated by Caspira SearchOps — ${new Date().toDateString()}`,
    'RewriteEngine On',
    '',
  ]
  redirects.forEach(r => {
    if (r.type === 410) {
      lines.push(`RewriteRule ^${r.from.slice(1)}$ - [G,L]`)
    } else {
      lines.push(`Redirect ${r.type} ${r.from} ${domain}${r.to}`)
    }
  })
  return lines.join('\n')
}

function toNginx(domain: string, redirects: Redirect[]): string {
  const lines = [`# Nginx redirects generated by Caspira SearchOps — ${new Date().toDateString()}`, '']
  redirects.forEach(r => {
    if (r.type === 410) {
      lines.push(`location = ${r.from} { return 410; }`)
    } else {
      lines.push(`location = ${r.from} { return ${r.type} ${domain}${r.to}; }`)
    }
  })
  return lines.join('\n')
}

let nextId = 100

export function RedirectManager() {
  const [redirects, setRedirects] = useState<Redirect[]>(DEFAULT_REDIRECTS)
  const [newFrom,   setNewFrom]   = useState('')
  const [newTo,     setNewTo]     = useState('')
  const [newType,   setNewType]   = useState<RedirectType>(301)
  const [domain,    setDomain]    = useState('https://yoursite.com')
  const [view,      setView]      = useState<ViewMode>('table')
  const [testUrl,   setTestUrl]   = useState('')
  const [testResult, setTestResult] = useState<string | null>(null)
  const [copied,    setCopied]    = useState(false)

  const processed = detectChains(redirects)
  const chains    = processed.filter(r => r.chain).length
  const temp302   = processed.filter(r => r.type === 302).length
  const gone410   = processed.filter(r => r.type === 410).length

  function addRedirect() {
    if (!newFrom.trim()) return
    const r: Redirect = {
      id: String(nextId++),
      from: newFrom.trim().startsWith('/') ? newFrom.trim() : `/${newFrom.trim()}`,
      to:   newTo.trim(),
      type: newType,
      chain: false,
      chainDepth: 1,
    }
    setRedirects(prev => detectChains([...prev, r]))
    setNewFrom(''); setNewTo('')
  }

  function remove(id: string) {
    setRedirects(prev => detectChains(prev.filter(r => r.id !== id)))
  }

  function testRedirect() {
    const path = testUrl.startsWith('/') ? testUrl : `/${testUrl}`
    let current = path
    const steps = [current]
    let hops = 0
    while (hops < 10) {
      const match = redirects.find(r => r.from === current)
      if (!match || match.type === 410) break
      current = match.to
      steps.push(current)
      hops++
      if (hops > 5) { setTestResult(`CHAIN TOO LONG: ${steps.join(' → ')} (${hops} hops)`); return }
    }
    if (steps.length === 1) setTestResult(`No redirect rule found for ${path}`)
    else setTestResult(`${steps.join(' → ')} (${hops} hop${hops > 1 ? 's' : ''})`)
  }

  const exportCode = view === 'htaccess' ? toHtaccess(domain, processed) : toNginx(domain, processed)

  function handleCopy() {
    navigator.clipboard.writeText(exportCode)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  function handleDownload() {
    const blob = new Blob([exportCode], { type: 'text/plain' })
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement('a')
    a.href = url
    a.download = view === 'htaccess' ? '.htaccess' : 'nginx-redirects.conf'
    a.click()
    URL.revokeObjectURL(url)
  }

  function exportCSV() {
    downloadCSV(
      `redirects-${new Date().toISOString().slice(0, 10)}.csv`,
      ['From Path', 'To Path', 'Type', 'Chain Warning'],
      processed.map(r => [r.from, r.to, TYPE_LABEL[r.type], r.chain ? 'Yes' : 'No']),
    )
  }

  return (
    <div className="space-y-5">
      {/* Stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {[
          { label: 'TOTAL RULES',    val: redirects.length, color: '#00d4ff', tip: 'Total number of redirect rules configured. Each rule maps an old URL to a new destination.' },
          { label: 'CHAIN WARNINGS', val: chains,           color: '#ef4444', tip: 'Redirect chains occur when the destination of one redirect is itself redirected. Chains waste crawl budget and dilute link equity — consolidate to single hops.' },
          { label: 'TEMP (302)',     val: temp302,          color: '#f59e0b', tip: '302 Temporary redirect — tells search engines the move is temporary. PageRank is not permanently transferred. Use 301 for permanent URL changes.' },
          { label: 'GONE (410)',     val: gone410,          color: '#7c3aed', tip: '410 Gone — signals that a page has been permanently removed with no replacement. Googlebot deindexes it faster than a 404.' },
        ].map(s => (
          <Card key={s.label} className="text-center py-4">
            <div className="text-3xl font-display font-black mb-1" style={{ color: s.color }}>{s.val}</div>
            <div className="flex items-center justify-center gap-1 text-[10px] text-muted font-mono-jarvis tracking-widest">
              {s.label}
              <InfoTooltip text={s.tip} />
            </div>
          </Card>
        ))}
      </div>

      {/* Add form */}
      <Card>
        <CardTitle className="mb-3">Add Redirect Rule</CardTitle>
        <div className="grid grid-cols-1 md:grid-cols-5 gap-2">
          <div className="md:col-span-2">
            <div className="text-[10px] text-muted font-mono-jarvis tracking-widest mb-1">FROM PATH</div>
            <input value={newFrom} onChange={e => setNewFrom(e.target.value)}
              onKeyDown={e => e.key === 'Enter' && addRedirect()}
              placeholder="/old-url-slug"
              className="w-full bg-surface border border-border rounded-lg px-3 py-2 text-xs text-tx font-mono-jarvis outline-none focus:border-accent transition-colors" />
          </div>
          <div className="md:col-span-2">
            <div className="text-[10px] text-muted font-mono-jarvis tracking-widest mb-1">TO PATH</div>
            <input value={newTo} onChange={e => setNewTo(e.target.value)}
              onKeyDown={e => e.key === 'Enter' && addRedirect()}
              placeholder="/new-url-slug (leave blank for 410)"
              className="w-full bg-surface border border-border rounded-lg px-3 py-2 text-xs text-tx font-mono-jarvis outline-none focus:border-accent transition-colors" />
          </div>
          <div>
            <div className="flex items-center gap-1 text-[10px] text-muted font-mono-jarvis tracking-widest mb-1">
              TYPE
              <InfoTooltip text="301 Permanent — passes full link equity, tells Google to update its index. 302 Temporary — preserves link equity on origin. 410 Gone — permanently deleted, no replacement." />
            </div>
            <div className="flex gap-1">
              {([301, 302, 410] as RedirectType[]).map(t => (
                <button key={t} onClick={() => setNewType(t)}
                  className={cn('flex-1 py-2 rounded-lg text-[11px] font-bold cursor-pointer border transition-all',
                    newType === t ? 'bg-accent text-black border-accent' : 'border-border text-muted hover:border-accent'
                  )}>{t}</button>
              ))}
            </div>
          </div>
        </div>
        <Button variant="primary" className="mt-3" onClick={addRedirect} disabled={!newFrom.trim()}>
          <Plus size={13} /> Add Rule
        </Button>
      </Card>

      {/* Redirect table */}
      <Card>
        <div className="flex items-center justify-between mb-4">
          <CardTitle>Redirect Rules</CardTitle>
          <div className="flex items-center gap-3">
            <button onClick={exportCSV}
              className="flex items-center gap-1 text-[11px] text-muted hover:text-accent transition-colors cursor-pointer">
              <Download size={11} /> Export CSV
            </button>
            <div className="flex gap-1.5">
              {(['table','htaccess','nginx'] as ViewMode[]).map(v => (
                <button key={v} onClick={() => setView(v)}
                  className={cn('text-[10px] px-2.5 py-1 rounded-lg font-mono-jarvis tracking-wide cursor-pointer transition-colors',
                    view === v ? 'bg-accent text-black' : 'text-muted hover:text-tx'
                  )}>{v === 'table' ? 'Table' : v === 'htaccess' ? '.htaccess' : 'Nginx'}</button>
              ))}
            </div>
          </div>
        </div>

        {view === 'table' ? (
          <div className="space-y-2">
            {chains > 0 && (
              <div className="flex items-center gap-2 p-3 bg-[#ef444415] border border-[#ef444430] rounded-lg mb-3">
                <AlertCircle size={13} className="text-danger shrink-0" />
                <div className="text-xs text-muted">
                  <span className="text-danger font-semibold">{chains} redirect chain{chains > 1 ? 's' : ''} detected</span>
                  {' '}— consolidate to single-hop redirects to preserve link equity.
                </div>
              </div>
            )}
            {processed.map(r => (
              <div key={r.id} className={cn(
                'flex items-center gap-3 p-3 rounded-xl border transition-colors',
                r.chain ? 'border-[#ef444440] bg-[#ef444408]' : 'border-border bg-surface'
              )}>
                {r.chain
                  ? <AlertCircle size={13} className="text-danger shrink-0" />
                  : <CheckCircle2 size={13} className="text-accent3 shrink-0" />
                }
                <div className="flex-1 min-w-0 flex items-center gap-2 flex-wrap">
                  <span className="text-xs font-mono-jarvis text-tx">{r.from}</span>
                  {r.type !== 410 && <ChevronRight size={11} className="text-muted shrink-0" />}
                  {r.type !== 410
                    ? <span className="text-xs font-mono-jarvis text-accent">{r.to}</span>
                    : <span className="text-xs text-danger font-mono-jarvis">GONE</span>
                  }
                  {r.chain && <Badge variant="red">Chain</Badge>}
                </div>
                <Badge variant={TYPE_BADGE[r.type]}>{r.type} {TYPE_LABEL[r.type]}</Badge>
                <button onClick={() => remove(r.id)} className="p-1.5 text-muted hover:text-danger transition-colors cursor-pointer shrink-0">
                  <Trash2 size={13} />
                </button>
              </div>
            ))}
          </div>
        ) : (
          <div>
            <div className="flex items-center gap-2 mb-3">
              <div>
                <div className="text-[10px] text-muted font-mono-jarvis tracking-widest mb-1">DOMAIN</div>
                <input value={domain} onChange={e => setDomain(e.target.value)}
                  className="bg-surface border border-border rounded-lg px-3 py-1.5 text-xs text-tx font-mono-jarvis outline-none focus:border-accent transition-colors w-60" />
              </div>
              <div className="flex gap-2 mt-4">
                <Button variant="ghost" className="text-[11px]" onClick={handleCopy}>
                  {copied ? <><Check size={11} /> Copied</> : <><Copy size={11} /> Copy</>}
                </Button>
                <Button variant="primary" className="text-[11px]" onClick={handleDownload}>
                  <Download size={11} /> Download
                </Button>
              </div>
            </div>
            <pre className="bg-code rounded-xl border border-border p-4 text-[11px] font-mono-jarvis text-accent3 overflow-x-auto whitespace-pre leading-relaxed">
              {exportCode}
            </pre>
          </div>
        )}
      </Card>

      {/* URL tester */}
      <Card>
        <CardTitle className="mb-3">Test Redirect Chain</CardTitle>
        <div className="flex gap-2">
          <input value={testUrl} onChange={e => setTestUrl(e.target.value)}
            onKeyDown={e => e.key === 'Enter' && testRedirect()}
            placeholder="/product-landing-page"
            className="flex-1 bg-surface border border-border rounded-lg px-3 py-2 text-xs text-tx font-mono-jarvis outline-none focus:border-accent transition-colors" />
          <Button variant="primary" onClick={testRedirect} disabled={!testUrl.trim()}>
            <Shuffle size={13} /> Test
          </Button>
        </div>
        {testResult && (
          <div className={cn(
            'mt-3 p-3 rounded-lg border text-xs font-mono-jarvis leading-relaxed',
            testResult.includes('CHAIN') ? 'bg-[#ef444415] border-[#ef444430] text-danger' :
            testResult.includes('No redirect') ? 'bg-surface border-border text-muted' :
            'bg-[#10b98110] border-[#10b98130] text-accent3'
          )}>
            {testResult}
          </div>
        )}
      </Card>
    </div>
  )
}
