import { useState } from 'react'
import { Map, Plus, Trash2, Copy, Check, Download, RefreshCw, ChevronDown, ChevronUp } from 'lucide-react'
import { Card, CardTitle } from '@/components/ui/Card'
import { Button } from '@/components/ui/Button'

interface SitemapUrl {
  id: string; path: string; priority: string; changefreq: string; lastmod: string; include: boolean
}

const CHANGE_FREQS = ['always', 'hourly', 'daily', 'weekly', 'monthly', 'yearly', 'never']
const PRIORITIES   = ['1.0', '0.9', '0.8', '0.7', '0.6', '0.5', '0.4', '0.3', '0.2', '0.1']
const TODAY        = new Date().toISOString().split('T')[0]

const DEFAULT_URLS: SitemapUrl[] = [
  { id: '1', path: '/', priority: '1.0', changefreq: 'daily', lastmod: TODAY, include: true },
]

function generateXML(domain: string, urls: SitemapUrl[]): string {
  const includedUrls = urls.filter(u => u.include)
  const entries = includedUrls.map(u =>
`  <url>
    <loc>${domain}${u.path}</loc>
    <lastmod>${u.lastmod}</lastmod>
    <changefreq>${u.changefreq}</changefreq>
    <priority>${u.priority}</priority>
  </url>`
  ).join('\n')

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Jarvis SEO Strategist — ${TODAY} -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries}
</urlset>`
}

let nextId = 200

export function SitemapGenerator() {
  const [domain,  setDomain]  = useState('')
  const [urls,    setUrls]    = useState<SitemapUrl[]>(DEFAULT_URLS)
  const [newPath, setNewPath] = useState('')
  const [view,    setView]    = useState<'table' | 'xml'>('table')
  const [copied,  setCopied]  = useState(false)
  const [showAll, setShowAll] = useState(false)

  const xml       = generateXML(domain, urls)
  const included  = urls.filter(u => u.include)
  const displayed = showAll ? urls : urls.slice(0, 8)

  function addUrl() {
    if (!newPath.trim()) return
    const path = newPath.trim().startsWith('/') ? newPath.trim() : `/${newPath.trim()}`
    const newUrl: SitemapUrl = { id: String(nextId++), path, priority: '0.7', changefreq: 'weekly', lastmod: TODAY, include: true }
    setUrls(prev => [...prev, newUrl])
    setNewPath('')
  }

  function updateUrl(id: string, field: keyof SitemapUrl, value: string | boolean) {
    setUrls(prev => prev.map(u => u.id === id ? { ...u, [field]: value } : u))
  }

  function removeUrl(id: string) {
    setUrls(prev => prev.filter(u => u.id !== id))
  }

  function handleCopy() {
    navigator.clipboard.writeText(xml)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  function handleDownload() {
    const blob = new Blob([xml], { type: 'application/xml' })
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement('a')
    a.href = url; a.download = 'sitemap.xml'; a.click()
    URL.revokeObjectURL(url)
  }

  function refreshAllDates() {
    setUrls(prev => prev.map(u => ({ ...u, lastmod: TODAY })))
  }

  return (
    <div className="space-y-5">
      {/* Stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {[
          { label: 'TOTAL URLS',    val: included.length,                                     color: '#00d4ff' },
          { label: 'PRIORITY 1.0',  val: included.filter(u => u.priority === '1.0').length,   color: '#10b981' },
          { label: 'DAILY REFRESH', val: included.filter(u => u.changefreq === 'daily').length, color: '#7c3aed' },
          { label: 'EXCLUDED',      val: urls.filter(u => !u.include).length,                  color: '#f59e0b' },
        ].map(s => (
          <Card key={s.label} className="text-center py-4">
            <div className="text-3xl font-display font-black mb-1" style={{ color: s.color }}>{s.val}</div>
            <div className="text-[10px] text-muted font-mono-jarvis tracking-widest">{s.label}</div>
          </Card>
        ))}
      </div>

      <Card>
        <div className="flex items-center justify-between mb-4">
          <CardTitle>XML Sitemap Generator</CardTitle>
          <div className="flex gap-2">
            <div>
              <input value={domain} onChange={e => setDomain(e.target.value)}
                className="bg-surface border border-border rounded-lg px-3 py-1.5 text-xs text-tx font-mono-jarvis outline-none focus:border-accent transition-colors w-52" />
            </div>
            <div className="flex gap-1.5">
              {(['table','xml'] as const).map(v => (
                <button key={v} onClick={() => setView(v)}
                  className={`text-[10px] px-2.5 py-1 rounded-lg font-mono-jarvis cursor-pointer transition-colors ${view === v ? 'bg-accent text-black' : 'text-muted hover:text-tx'}`}>
                  {v === 'table' ? 'Editor' : 'XML Preview'}
                </button>
              ))}
            </div>
          </div>
        </div>

        {view === 'table' ? (
          <>
            {/* Add URL */}
            <div className="flex gap-2 mb-4">
              <input value={newPath} onChange={e => setNewPath(e.target.value)}
                onKeyDown={e => e.key === 'Enter' && addUrl()}
                placeholder="/new-casino-page"
                className="flex-1 bg-surface border border-border rounded-lg px-3 py-2 text-xs text-tx font-mono-jarvis outline-none focus:border-accent transition-colors" />
              <Button variant="primary" onClick={addUrl} disabled={!newPath.trim()}>
                <Plus size={13} /> Add URL
              </Button>
              <Button variant="ghost" className="text-[11px]" onClick={refreshAllDates}>
                <RefreshCw size={11} /> Refresh Dates
              </Button>
            </div>

            {/* URL table */}
            <div className="space-y-1.5">
              {/* Header */}
              <div className="grid grid-cols-12 gap-2 px-2 text-[10px] text-muted font-mono-jarvis tracking-widest">
                <div className="col-span-1">INC</div>
                <div className="col-span-4">PATH</div>
                <div className="col-span-2">PRIORITY</div>
                <div className="col-span-3">CHANGEFREQ</div>
                <div className="col-span-2">LASTMOD</div>
              </div>

              {displayed.map(url => (
                <div key={url.id} className="grid grid-cols-12 gap-2 items-center p-2 bg-surface border border-border rounded-lg">
                  <div className="col-span-1">
                    <input type="checkbox" checked={url.include}
                      onChange={e => updateUrl(url.id, 'include', e.target.checked)}
                      className="w-3.5 h-3.5 accent-accent cursor-pointer" />
                  </div>
                  <div className="col-span-4">
                    <div className="text-xs font-mono-jarvis text-tx truncate">{url.path}</div>
                  </div>
                  <div className="col-span-2">
                    <select value={url.priority} onChange={e => updateUrl(url.id, 'priority', e.target.value)}
                      className="w-full bg-card border border-border rounded px-1.5 py-1 text-[11px] text-tx font-mono-jarvis outline-none focus:border-accent">
                      {PRIORITIES.map(p => <option key={p}>{p}</option>)}
                    </select>
                  </div>
                  <div className="col-span-3">
                    <select value={url.changefreq} onChange={e => updateUrl(url.id, 'changefreq', e.target.value)}
                      className="w-full bg-card border border-border rounded px-1.5 py-1 text-[11px] text-tx font-mono-jarvis outline-none focus:border-accent">
                      {CHANGE_FREQS.map(f => <option key={f}>{f}</option>)}
                    </select>
                  </div>
                  <div className="col-span-1">
                    <div className="text-[10px] font-mono-jarvis text-muted">{url.lastmod.slice(5)}</div>
                  </div>
                  <button onClick={() => removeUrl(url.id)} className="col-span-1 text-muted hover:text-danger transition-colors cursor-pointer justify-self-end">
                    <Trash2 size={12} />
                  </button>
                </div>
              ))}

              {urls.length > 8 && (
                <button onClick={() => setShowAll(s => !s)}
                  className="flex items-center gap-1 text-[11px] text-accent hover:underline cursor-pointer mt-1 px-2">
                  {showAll ? <><ChevronUp size={12} /> Show less</> : <><ChevronDown size={12} /> Show all {urls.length} URLs</>}
                </button>
              )}
            </div>
          </>
        ) : (
          <>
            <div className="flex gap-2 mb-3">
              <Button variant="ghost" className="text-[11px]" onClick={handleCopy}>
                {copied ? <><Check size={11} /> Copied</> : <><Copy size={11} /> Copy XML</>}
              </Button>
              <Button variant="primary" className="text-[11px]" onClick={handleDownload}>
                <Download size={11} /> Download sitemap.xml
              </Button>
            </div>
            <pre className="bg-code rounded-xl border border-border p-4 text-[10px] font-mono-jarvis text-accent3 overflow-x-auto whitespace-pre leading-relaxed max-h-96 overflow-y-auto scrollbar-thin">
              {xml}
            </pre>
          </>
        )}

        <div className="mt-4 grid grid-cols-3 gap-3">
          {[
            { tip: 'Priority 1.0 should only be used for your most important pages — pillar casino pages and homepage.' },
            { tip: 'Set changefreq="daily" for bonus pages updated regularly; "weekly" for evergreen casino reviews.' },
            { tip: 'Submit your sitemap in Google Search Console after downloading for faster indexing of casino content.' },
          ].map((t, i) => (
            <div key={i} className="p-3 bg-surface border border-border rounded-lg text-[10px] text-muted leading-relaxed">
              <Map size={11} className="text-accent mb-1" />{t.tip}
            </div>
          ))}
        </div>
      </Card>
    </div>
  )
}
